In [2]:
import pandas as pd

In [3]:
%ls

Données_POC2024_2025_10122025.xls    fisprod_acorig.csv
PyTorchGPUM2Pro.ipynb                fisprod_valide.csv
VerificationService.php              pipeline.ipynb
best_model_mps.pt                    rapport_classification_torch.txt
chapipeline.ipynb                    statistiques_dataframe.txt

In [4]:
df1 = pd.read_excel("Données_POC2024_2025_10122025.xls")
print(df1.head())

           Pays Région Province District sanitaire Commune/arrondissement  \
0  Burkina Faso  Nando  Sissili             DS Léo                  Boura
1  Burkina Faso  Nando  Sissili             DS Léo                  Boura
2  Burkina Faso  Nando  Sissili             DS Léo                  Boura
3  Burkina Faso  Nando  Sissili             DS Léo                  Boura
4  Burkina Faso  Nando  Sissili             DS Léo                  Boura

  Formation sanitaire       Période  \
0           BHM Boura     Mars 2025
1           BHM Boura  Février 2025
2           BHM Boura  Janvier 2025
3           BHM Boura    Avril 2025
4           BHM Boura  Octobre 2025

   Décès maternels par cause de complication obstétricale  \
0                                                0.0
1                                                0.0
2                                                0.0
3                                                0.0
4                                                0.0

   Décès maternels par cause de complication obstétricale Autres complications obstétricales  \
0                                                0.0
1                                                0.0
2                                                0.0
3                                                0.0
4                                                0.0

   Décès maternels par cause de complication obstétricale Complications avortements  \
0                                                0.0
1                                                0.0
2                                                0.0
3                                                0.0
4                                                0.0

   ...  Nombre de décès maternel en communauté  \
0  ...                                     NaN
1  ...                                     NaN
2  ...                                     NaN
3  ...                                     NaN
4  ...                                     NaN

   Nombre de décès maternels audités  Nombre de décès néonatal en communauté  \
0                                0.0                                     NaN
1                                0.0                                     NaN
2                                0.0                                     NaN
3                                0.0                                     NaN
4                                0.0                                     NaN

   Nouveau-nes decedes de 0-6 jours  Nouveau-nes decedes de 7-28 jours  \
0                               0.0                                0.0
1                               0.0                                0.0
2                               0.0                                0.0
3                               0.0                                0.0
4                               0.0                                0.0

   SMI-Proportion de deces maternels audites  \
0                                        NaN
1                                        NaN
2                                        NaN
3                                        NaN
4                                        NaN

   SMI-Proportion de deces maternels pour 100 000 parturientes  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

   SMI-Proportion de deces neonatals audites  \
0                                        NaN
1                                        NaN
2                                        NaN
3                                        NaN
4                                        NaN

   SMI-Proportion de décès néonatal parmis les naissances vivantes  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

   SMI-Proportion de femmes vues au 1er trimestre pour la CPN1
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

[5 rows x 28 columns]

In [5]:
# Dimensions
print("Dimensions (lignes, colonnes) :", df1.shape)

# Types des colonnes
print("\nTypes de données :")
print(df1.dtypes)

# Vue générale
print("\nInfo générale :")
df1.info()

Dimensions (lignes, colonnes) : (57829, 28)

Types de données :
Pays                                                                                          object
Région                                                                                        object
Province                                                                                      object
District sanitaire                                                                            object
Commune/arrondissement                                                                        object
Formation sanitaire                                                                           object
Période                                                                                       object
Décès maternels par cause de complication obstétricale                                       float64
Décès maternels par cause de complication obstétricale Autres complications obstétricales    float64
Décès maternels par cause de complication obstétricale Complications avortements             float64
Décès maternels par cause de complication obstétricale Disproportion foeto-pelvienne         float64
Décès maternels par cause de complication obstétricale Eclampsie                             float64
Décès maternels par cause de complication obstétricale GEU                                   float64
Décès maternels par cause de complication obstétricale Hémorragie                            float64
Décès maternels par cause de complication obstétricale Infections                            float64
Décès maternels par cause de complication obstétricale Présentation vicieuse                 float64
Décès maternels par cause de complication obstétricale Rupture utérine                       float64
Décès maternels par cause de complication obstétricale Rétentions placentaire                float64
Nombre de décès maternel en communauté                                                       float64
Nombre de décès maternels audités                                                            float64
Nombre de décès néonatal en communauté                                                       float64
Nouveau-nes decedes de 0-6 jours                                                             float64
Nouveau-nes decedes de 7-28 jours                                                            float64
SMI-Proportion de deces maternels audites                                                    float64
SMI-Proportion de deces maternels pour 100 000 parturientes                                  float64
SMI-Proportion de deces neonatals audites                                                    float64
SMI-Proportion de décès néonatal parmis les naissances vivantes                              float64
SMI-Proportion de femmes vues au 1er trimestre pour la CPN1                                  float64
dtype: object

Info générale :
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 57829 entries, 0 to 57828
Data columns (total 28 columns):
 #   Column                                                                                     Non-Null Count  Dtype
---  ------                                                                                     --------------  -----
 0   Pays                                                                                       57829 non-null  object
 1   Région                                                                                     57829 non-null  object
 2   Province                                                                                   57829 non-null  object
 3   District sanitaire                                                                         57829 non-null  object
 4   Commune/arrondissement                                                                     57829 non-null  object
 5   Formation sanitaire                                                                        57829 non-null  object
 6   Période                                                                                    57829 non-null  object
 7   Décès maternels par cause de complication obstétricale                                     45539 non-null  float64
 8   Décès maternels par cause de complication obstétricale Autres complications obstétricales  45121 non-null  float64
 9   Décès maternels par cause de complication obstétricale Complications avortements           45167 non-null  float64
 10  Décès maternels par cause de complication obstétricale Disproportion foeto-pelvienne       44757 non-null  float64
 11  Décès maternels par cause de complication obstétricale Eclampsie                           45238 non-null  float64
 12  Décès maternels par cause de complication obstétricale GEU                                 45175 non-null  float64
 13  Décès maternels par cause de complication obstétricale Hémorragie                          44648 non-null  float64
 14  Décès maternels par cause de complication obstétricale Infections                          45173 non-null  float64
 15  Décès maternels par cause de complication obstétricale Présentation vicieuse               44685 non-null  float64
 16  Décès maternels par cause de complication obstétricale Rupture utérine                     45194 non-null  float64
 17  Décès maternels par cause de complication obstétricale Rétentions placentaire              44643 non-null  float64
 18  Nombre de décès maternel en communauté                                                     11340 non-null  float64
 19  Nombre de décès maternels audités                                                          41130 non-null  float64
 20  Nombre de décès néonatal en communauté                                                     11340 non-null  float64
 21  Nouveau-nes decedes de 0-6 jours                                                           47449 non-null  float64
 22  Nouveau-nes decedes de 7-28 jours                                                          47168 non-null  float64
 23  SMI-Proportion de deces maternels audites                                                  419 non-null    float64
 24  SMI-Proportion de deces maternels pour 100 000 parturientes                                39524 non-null  float64
 25  SMI-Proportion de deces neonatals audites                                                  1750 non-null   float64
 26  SMI-Proportion de décès néonatal parmis les naissances vivantes                            41379 non-null  float64
 27  SMI-Proportion de femmes vues au 1er trimestre pour la CPN1                                51343 non-null  float64
dtypes: float64(21), object(7)
memory usage: 12.4+ MB

In [6]:
df1.describe(include="all")

,Pays,Région,Province,District sanitaire,Commune/arrondissement,Formation sanitaire,Période,Décès maternels par cause de complication obstétricale,Décès maternels par cause de complication obstétricale Autres complications obstétricales,Décès maternels par cause de complication obstétricale Complications avortements,...,Nombre de décès maternel en communauté,Nombre de décès maternels audités,Nombre de décès néonatal en communauté,Nouveau-nes decedes de 0-6 jours,Nouveau-nes decedes de 7-28 jours,SMI-Proportion de deces maternels audites,SMI-Proportion de deces maternels pour 100 000 parturientes,SMI-Proportion de deces neonatals audites,SMI-Proportion de décès néonatal parmis les naissances vivantes,SMI-Proportion de femmes vues au 1er trimestre pour la CPN1
count,57829,57829,57829,57829,57829,57829,57829,45539.000000,45121.000000,45167.000000,...,11340.000000,41130.000000,11340.000000,47449.000000,47168.000000,419.000000,39524.000000,1750.000000,41379.000000,51343.000000
unique,1,17,45,70,412,3243,22,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,Burkina Faso,Kadiogo,Kadiogo,DS Boulmiougou,Koudougou,CSPS Tanghin,Février 2025,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,57829,7830,7830,2292,1110,88,2773,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.012385,0.004654,0.000421,...,0.005379,0.012546,0.005026,0.076187,0.010961,80.688138,33.970653,22.531663,0.292090,49.572815
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.142985,0.076640,0.020506,...,0.210550,0.156203,0.181301,0.570512,0.230286,46.499593,769.733652,66.266699,2.926227,27.246515
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,100.000000,0.000000,0.000000,0.000000,29.630000
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,100.000000,0.000000,0.000000,0.000000,47.060000
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,100.000000,0.000000,0.000000,0.000000,66.670000
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.000000,4.000000,1.000000,...,9.000000,9.000000,9.000000,41.000000,34.000000,300.000000,100000.000000,1000.000000,200.000000,500.000000

In [7]:
df1.describe()

,Décès maternels par cause de complication obstétricale,Décès maternels par cause de complication obstétricale Autres complications obstétricales,Décès maternels par cause de complication obstétricale Complications avortements,Décès maternels par cause de complication obstétricale Disproportion foeto-pelvienne,Décès maternels par cause de complication obstétricale Eclampsie,Décès maternels par cause de complication obstétricale GEU,Décès maternels par cause de complication obstétricale Hémorragie,Décès maternels par cause de complication obstétricale Infections,Décès maternels par cause de complication obstétricale Présentation vicieuse,Décès maternels par cause de complication obstétricale Rupture utérine,...,Nombre de décès maternel en communauté,Nombre de décès maternels audités,Nombre de décès néonatal en communauté,Nouveau-nes decedes de 0-6 jours,Nouveau-nes decedes de 7-28 jours,SMI-Proportion de deces maternels audites,SMI-Proportion de deces maternels pour 100 000 parturientes,SMI-Proportion de deces neonatals audites,SMI-Proportion de décès néonatal parmis les naissances vivantes,SMI-Proportion de femmes vues au 1er trimestre pour la CPN1
count,45539.000000,45121.000000,45167.000000,44757.000000,45238.000000,45175.000000,44648.000000,45173.000000,44685.000000,45194.000000,...,11340.000000,41130.000000,11340.000000,47449.000000,47168.000000,419.000000,39524.000000,1750.000000,41379.000000,51343.000000
mean,0.012385,0.004654,0.000421,0.000179,0.000862,0.000332,0.003561,0.001218,0.000224,0.000885,...,0.005379,0.012546,0.005026,0.076187,0.010961,80.688138,33.970653,22.531663,0.292090,49.572815
std,0.142985,0.076640,0.020506,0.013368,0.029349,0.019396,0.061785,0.065014,0.014958,0.029737,...,0.210550,0.156203,0.181301,0.570512,0.230286,46.499593,769.733652,66.266699,2.926227,27.246515
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,100.000000,0.000000,0.000000,0.000000,29.630000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,100.000000,0.000000,0.000000,0.000000,47.060000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,100.000000,0.000000,0.000000,0.000000,66.670000
max,12.000000,4.000000,1.000000,1.000000,1.000000,2.000000,2.000000,12.000000,1.000000,1.000000,...,9.000000,9.000000,9.000000,41.000000,34.000000,300.000000,100000.000000,1000.000000,200.000000,500.000000

In [9]:
df1.isna().sum()

Pays                                                                                          0.000000
Région                                                                                        0.000000
Province                                                                                      0.000000
District sanitaire                                                                            0.000000
Commune/arrondissement                                                                        0.000000
Formation sanitaire                                                                           0.000000
Période                                                                                       0.000000
Décès maternels par cause de complication obstétricale                                       21.252313
Décès maternels par cause de complication obstétricale Autres complications obstétricales    21.975134
Décès maternels par cause de complication obstétricale Complications avortements             21.895589
Décès maternels par cause de complication obstétricale Disproportion foeto-pelvienne         22.604576
Décès maternels par cause de complication obstétricale Eclampsie                             21.772813
Décès maternels par cause de complication obstétricale GEU                                   21.881755
Décès maternels par cause de complication obstétricale Hémorragie                            22.793062
Décès maternels par cause de complication obstétricale Infections                            21.885213
Décès maternels par cause de complication obstétricale Présentation vicieuse                 22.729081
Décès maternels par cause de complication obstétricale Rupture utérine                       21.848899
Décès maternels par cause de complication obstétricale Rétentions placentaire                22.801708
Nombre de décès maternel en communauté                                                       80.390462
Nombre de décès maternels audités                                                            28.876515
Nombre de décès néonatal en communauté                                                       80.390462
Nouveau-nes decedes de 0-6 jours                                                             17.949472
Nouveau-nes decedes de 7-28 jours                                                            18.435387
SMI-Proportion de deces maternels audites                                                    99.275450
SMI-Proportion de deces maternels pour 100 000 parturientes                                  31.653669
SMI-Proportion de deces neonatals audites                                                    96.973837
SMI-Proportion de décès néonatal parmis les naissances vivantes                              28.445935
SMI-Proportion de femmes vues au 1er trimestre pour la CPN1                                  11.215826
dtype: float64

In [10]:
(df1.isna().sum() / len(df1)) * 100

Pays                                                                                          0.000000
Région                                                                                        0.000000
Province                                                                                      0.000000
District sanitaire                                                                            0.000000
Commune/arrondissement                                                                        0.000000
Formation sanitaire                                                                           0.000000
Période                                                                                       0.000000
Décès maternels par cause de complication obstétricale                                       21.252313
Décès maternels par cause de complication obstétricale Autres complications obstétricales    21.975134
Décès maternels par cause de complication obstétricale Complications avortements             21.895589
Décès maternels par cause de complication obstétricale Disproportion foeto-pelvienne         22.604576
Décès maternels par cause de complication obstétricale Eclampsie                             21.772813
Décès maternels par cause de complication obstétricale GEU                                   21.881755
Décès maternels par cause de complication obstétricale Hémorragie                            22.793062
Décès maternels par cause de complication obstétricale Infections                            21.885213
Décès maternels par cause de complication obstétricale Présentation vicieuse                 22.729081
Décès maternels par cause de complication obstétricale Rupture utérine                       21.848899
Décès maternels par cause de complication obstétricale Rétentions placentaire                22.801708
Nombre de décès maternel en communauté                                                       80.390462
Nombre de décès maternels audités                                                            28.876515
Nombre de décès néonatal en communauté                                                       80.390462
Nouveau-nes decedes de 0-6 jours                                                             17.949472
Nouveau-nes decedes de 7-28 jours                                                            18.435387
SMI-Proportion de deces maternels audites                                                    99.275450
SMI-Proportion de deces maternels pour 100 000 parturientes                                  31.653669
SMI-Proportion de deces neonatals audites                                                    96.973837
SMI-Proportion de décès néonatal parmis les naissances vivantes                              28.445935
SMI-Proportion de femmes vues au 1er trimestre pour la CPN1                                  11.215826
dtype: float64

In [11]:
for col in df1.select_dtypes(include="object").columns:
    print("\nDistribution de :", col)
    print(df1[col].value_counts())

Distribution de : Pays
Pays
Burkina Faso    57829
Name: count, dtype: int64

Distribution de : Région
Région
Kadiogo       7830
Nando         6702
Guiriko       6372
Nakambé       5091
Oubri         4743
Yaadga        4519
Nazinon       3755
Djoro         3517
Bankui        3287
Tannounyan    3045
Koulsé        2931
Sourou        1927
Goulmou       1126
Sirba         1077
Liptako        971
Tapoa          706
Soum           230
Name: count, dtype: int64

Distribution de : Province
Province
Kadiogo       7830
Houet         3912
Boulkiemdé    3325
Boulgou       2597
Comoé         2216
Oubritenga    2080
Yatenga       1876
Ganzourgou    1828
Sanmatenga    1770
Kouritenga    1764
Bazega        1637
Passoré       1551
Mouhoun       1446
Kenedougou    1380
Sanguié       1337
Poni          1321
Bale          1266
Zoundweogo    1214
Sissili       1207
Ioba          1120
Tuy           1080
Gourma        1034
Nahouri        904
Zondoma        895
Gnagna         881
Kourweogo      835
Ziro           833
Leraba         829
Kossi          780
Koulpélogo     730
Tapoa          706
Bougouriba     684
Namentenga     613
Sourou         593
Banwa          575
Nayala         554
Bam            548
Oudalan        508
Noumbiel       392
Seno           281
Soum           230
Loroum         197
Komandjari     196
Yagha          182
Kompienga       92
Name: count, dtype: int64

Distribution de : District sanitaire
District sanitaire
DS Boulmiougou    2292
DS Ziniaré        2080
DS Bogodogo       2039
DS Koudougou      1997
DS Sig-Noghin     1876
                  ...
DS Sebba           182
DS Tougouri        172
DS Pama             92
DS Barsalogho       82
DS Thiou            53
Name: count, Length: 70, dtype: int64

Distribution de : Commune/arrondissement
Commune/arrondissement
Koudougou                     1110
Ouaga Arrondissement 9 SNG     961
Banfora                        812
Ziniare                        735
Ouaga Arrondissement 7         680
                              ...
Ouindigui                        9
Kelbo                            9
Banh                             8
Ouaga Arrondissement 1 BMG       8
Tankougounadjé                   1
Name: count, Length: 412, dtype: int64

Distribution de : Formation sanitaire
Formation sanitaire
CSPS Tanghin                                   88
CSPS Mou                                       66
CSPS Namassa                                   66
CSPS Yargo                                     66
CSPS Koro                                      66
                                               ..
Clinique Ouris                                  1
Cabinet de soins infirmiers Laafi Gninta        1
Cabinet de soins infirmiers sainte Hortence     1
Infirmerie Lycée communal de Tenkodogo          1
Cabinet de soins infirmiers la Grace            1
Name: count, Length: 3243, dtype: int64

Distribution de : Période
Période
Février 2025      2773
Mars 2025         2763
Janvier 2025      2751
Novembre 2024     2722
Juillet 2025      2701
Mai 2025          2698
Octobre 2024      2697
Juin 2025         2688
Décembre 2024     2685
Avril 2025        2670
Septembre 2024    2667
Septembre 2025    2658
Août 2025         2649
Août 2024         2619
Octobre 2025      2610
Juillet 2024      2573
Juin 2024         2534
Avril 2024        2507
Mai 2024          2498
Mars 2024         2486
Janvier 2024      2441
Février 2024      2439
Name: count, dtype: int64